import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "淡江畢業祝福",
  description: "Generated by 數位燈塔",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-screen h-screen">
        <div className="w-full h-full bg-sky-100">{children}</div>
      </body>
    </html>
  );
}
